[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "pip install hatchling",
    "pip install -e ."
]

[start]
cmd = "python -m uvicorn services.seller.main:app --host 0.0.0.0 --port $PORT"
