[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = [
  "python -m ensurepip",
  "python -m pip install --upgrade pip",
  "pip install uv",
  "uv sync"
]

[start]
cmd = "uvicorn services.seller.main:app --host 0.0.0.0 --port $PORT"
